task :default => [:preview]

task :preview do
  puts 'server runing'
  commands = {
    :jekyll => 'jekyll --auto',
    :compass => 'compass watch',
    :guard => 'guard',
    :rackup => 'rackup --port 4000'
  }

  pids = commands.map { |command| Process.spawn(command.last) }

  pids.each { |pid| Process.wait(pid) }

  trap('INT') do
    pids.each { |pid| Process.kill(9, pid) rescue Errno::ESRCH }
    exit 0
  end
end

